# Data Configuration
processed_data: data/processed/icu_master.csv
target_col: event
time_col: time
features:
  numerical:
    - age
    - height
    - weight
    - hour_of_admission
  categorical:
    - sex
    - unit_type
    - admission_location
    - race
    - gcs_motor
    - gcs_verbal
