# config/features.yaml

features:
  # Identifiers and target variables that should NOT be part of the feature matrix X
  ignore_cols:
    - patientunitstayid
    - uniquepid
    - patienthealthsystemstayid
    - actualhospitalmortality
    - actualiculos

  # Categorical features
  categorical:
    - gender
    - ethnicity
    - first_careunit
    - admission_location
    - insurance

  # Numerical features 
  numerical:
    - age
    - hour
    - eyes
    - height
    - motor
    - verbal
    - weight
