experiment:
  name: landmark_static_pycox
  prediction_time_hours: 72
  max_horizon_days: 10
  time_unit: days_since_72h
  num_durations: 10

paths:
  processed_dir: data/processed/landmark_72h/static
  outputs_dir: outputs/landmark_72h/static

evaluation:
  metric_integration_num_points: 100
  horizon_times: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  save_example_curves: true
  n_example_patients: 9

tuning:
  seed: 42
  objective:
    primary_metric: validation_ctd_antolini
    primary_direction: maximize
    tiebreaker_metric: validation_ibll
    tiebreaker_direction: minimize

final:
  seeds: [42, 123, 2026]

models:
  kaplan_meier:
    grid:
      save_model: [false]

  coxph:
    grid:
      penalizer: [0.0003, 0.001, 0.003, 0.005, 0.01]
      l1_ratio: [0.0, 0.05, 0.1]
      save_model: [false]

  random_survival_forest:
    grid:
      n_estimators: [500]
      min_samples_leaf: [5, 15, 30]
      min_samples_split: [10, 20]
      max_features: [sqrt, 0.5]
      max_depth: [null]
      bootstrap: [true]
      low_memory: [false]
      n_jobs: [4]
      verbose: [0]
      save_model: [false]

  deepsurv:
    grid:
      hidden_layers:
        - [128, 64]
        - [128, 64, 32]
      dropout: [0.1, 0.2]
      batch_norm: [true]
      learning_rate: [0.0005, 0.001]
      weight_decay: [0.0001, 0.001]
      batch_size: [256]
      epochs: [256]
      early_stopping: [true]
      patience: [20]
      sub: [10]
      verbose: [false]
      save_model: [false]

  logistic_hazard:
    grid:
      num_durations: [11]
      hidden_layers:
        - [128, 64]
        - [128, 64, 32]
      dropout: [0.1, 0.2]
      batch_norm: [true]
      learning_rate: [0.0005, 0.0008]
      weight_decay: [0.0, 0.00001]
      batch_size: [256]
      epochs: [256]
      early_stopping: [true]
      patience: [20]
      interpolate: [10]
      verbose: [false]
      save_model: [false]

  pchazard:
    grid:
      num_durations: [10]
      hidden_layers:
        - [64, 32]
        - [128, 64]
      dropout: [0.3, 0.4]
      batch_norm: [true]
      learning_rate: [0.0005, 0.0008]
      weight_decay: [0.0, 0.00001]
      batch_size: [256]
      epochs: [256]
      early_stopping: [true]
      patience: [20]
      sub: [10]
      verbose: [false]
      save_model: [false]

  deephit_single:
    grid:
      num_durations: [11]
      hidden_layers:
        - [64, 32]
        - [128, 64, 32]
      dropout: [0.3, 0.4]
      batch_norm: [true]
      learning_rate: [0.0005, 0.0008]
      weight_decay: [0.0]
      batch_size: [256]
      alpha: [0.2, 0.3]
      sigma: [0.1]
      epochs: [256]
      early_stopping: [true]
      patience: [20]
      interpolate: [10]
      verbose: [false]
      save_model: [false]
