run_build_static_data: false
run_evaluation: true

static_data_config: configs/static_data.yaml
evaluation_config: configs/static_evaluation.yaml

model_configs:
  - configs/kaplan_meier.yaml
  - configs/coxph.yaml
  - configs/deepsurv.yaml
  - configs/pchazard.yaml
  - configs/deephit.yaml
